# Generated by Django 5.2.12 on 2026-03-19 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
