# Generated by Django 5.2.12 on 2026-03-25 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_cluster_station_address_alter_customuser_station_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cluster',
            name='code',
            field=models.CharField(default='A', max_length=5),
            preserve_default=False,
        ),
    ]
