# Generated by Django 5.2.12 on 2026-03-25 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_cluster_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='tank_capacity',
            field=models.IntegerField(default=16000),
        ),
    ]
