# Generated by Django 5.2.12 on 2026-03-26 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_station_tank_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='diesel_capacity',
            field=models.IntegerField(default=16000),
        ),
        migrations.AddField(
            model_name='station',
            name='premium_capacity',
            field=models.IntegerField(default=16000),
        ),
        migrations.AddField(
            model_name='station',
            name='regular_capacity',
            field=models.IntegerField(default=16000),
        ),
    ]
