# Generated by Django 5.2.12 on 2026-03-28 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_station_diesel_capacity_station_premium_capacity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='diesel_capacity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='station',
            name='premium_capacity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='station',
            name='regular_capacity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
