# Generated by Django 5.2.12 on 2026-03-28 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_station_diesel_capacity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='tank_capacity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
