# Generated by Django 5.2.12 on 2026-03-28 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_alter_station_tank_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='cluster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cluster', to='account.cluster'),
        ),
    ]
