# Generated by Django 5.2.12 on 2026-03-30 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_customuser_cluster'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='cluster',
        ),
    ]
