# Generated by Django 5.2.12 on 2026-04-10 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_alter_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='allowed_tanks',
            field=models.CharField(default='T1,T2,T3', max_length=10),
        ),
    ]
