# Generated by Django 5.2.12 on 2026-04-11 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_station_allowed_tanks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='station',
        ),
        migrations.AddField(
            model_name='customuser',
            name='stations',
            field=models.ManyToManyField(blank=True, related_name='assigned_users', to='account.station'),
        ),
    ]
