# Generated by Django 5.2.12 on 2026-04-11 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_remove_customuser_station_customuser_stations'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='stations',
            new_name='station',
        ),
    ]
