# Generated by Django 5.2.12 on 2026-04-16 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_customuser_activation_sent_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_activated',
            field=models.BooleanField(default=False),
        ),
    ]
