# Generated by Django 5.2.12 on 2026-04-21 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_customuser_is_activated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('staff', 'Staff'), ('admin', 'Admin'), ('viewer', 'Viewer')], default='staff', max_length=20),
        ),
    ]
