# Generated by Django 5.2.12 on 2026-03-09 06:14

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FuelSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuel_type', models.CharField(choices=[('Premium', 'Premium'), ('Diesel', 'Diesel'), ('Regular', 'Regular')], default='Premium', max_length=20)),
                ('tank', models.CharField(choices=[('T1', 'Tank 1'), ('T2', 'Tank 2'), ('T3', 'Tank 3')], default='T1', max_length=10)),
                ('opening', models.FloatField(default=0)),
                ('closing', models.FloatField(default=0)),
                ('liters_sold', models.FloatField(blank=True, null=True)),
                ('date', models.DateField(default=datetime.date.today)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.station')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
