# Generated by Django 5.2.12 on 2026-03-11 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuelsale',
            name='fuel_type',
            field=models.CharField(choices=[('Premium', 'Premium'), ('Diesel', 'Diesel'), ('ULG', 'Unleaded Gasoline')], max_length=20),
        ),
        migrations.AlterField(
            model_name='fuelsale',
            name='tank',
            field=models.CharField(choices=[('T1', 'Tank 1'), ('T2', 'Tank 2'), ('T3', 'Tank 3')], max_length=10),
        ),
    ]
