# Generated by Django 5.2.12 on 2026-03-12 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_alter_fuelsale_fuel_type_alter_fuelsale_tank'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuelsale',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
