# Generated by Django 5.2.12 on 2026-03-12 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_fuelsale_is_read'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuelPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuel_type', models.CharField(choices=[('Premium', 'Premium'), ('Diesel', 'Diesel'), ('ULG', 'ULG')], max_length=20)),
                ('price', models.FloatField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
