# Generated by Django 5.2.12 on 2026-03-13 01:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0005_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuelsale',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
