# Generated by Django 5.2.12 on 2026-03-13 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0006_fuelsale_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fuelsale',
            options={'ordering': ['-created_at']},
        ),
    ]
