# Generated by Django 5.2.12 on 2026-03-14 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0007_alter_fuelsale_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fuelsale',
            old_name='closing',
            new_name='tank1_income',
        ),
        migrations.RenameField(
            model_name='fuelsale',
            old_name='opening',
            new_name='tank2_income',
        ),
        migrations.RemoveField(
            model_name='fuelsale',
            name='liters_sold',
        ),
        migrations.RemoveField(
            model_name='fuelsale',
            name='tank',
        ),
        migrations.AddField(
            model_name='fuelsale',
            name='tank3_income',
            field=models.FloatField(default=0),
        ),
    ]
