# Generated by Django 5.2.12 on 2026-03-16 00:33

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('staff', '0008_rename_closing_fuelsale_tank1_income_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FuelSale',
            new_name='FuelInventory',
        ),
    ]
