# Generated by Django 5.2.12 on 2026-03-16 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0009_rename_fuelsale_fuelinventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuelinventory',
            name='cm',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fuelinventory',
            name='liters',
            field=models.IntegerField(default=0),
        ),
    ]
