# Generated by Django 5.2.12 on 2026-03-16 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0010_fuelinventory_cm_fuelinventory_liters'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FuelPrice',
        ),
    ]
