# Generated by Django 5.2.12 on 2026-03-16 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0011_delete_fuelprice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fuelinventory',
            old_name='cm',
            new_name='tank1_liters',
        ),
        migrations.RenameField(
            model_name='fuelinventory',
            old_name='liters',
            new_name='tank2_liters',
        ),
        migrations.RemoveField(
            model_name='fuelinventory',
            name='tank1_income',
        ),
        migrations.RemoveField(
            model_name='fuelinventory',
            name='tank2_income',
        ),
        migrations.RemoveField(
            model_name='fuelinventory',
            name='tank3_income',
        ),
        migrations.AddField(
            model_name='fuelinventory',
            name='tank1_cm',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='fuelinventory',
            name='tank2_cm',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='fuelinventory',
            name='tank3_cm',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='fuelinventory',
            name='tank3_liters',
            field=models.IntegerField(default=0),
        ),
    ]
