# Generated by Django 5.2.12 on 2026-03-25 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0012_rename_cm_fuelinventory_tank1_liters_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuelinventory',
            name='dispatch_liters',
            field=models.FloatField(default=0),
        ),
    ]
