# Generated by Django 5.2.12 on 2026-04-04 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_alter_customuser_first_name_and_more'),
        ('staff', '0014_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='StationDispatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuel_type', models.CharField(max_length=50)),
                ('dispatch_liters', models.FloatField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.station')),
            ],
            options={
                'unique_together': {('station', 'fuel_type')},
            },
        ),
    ]
