# Generated by Django 5.2.12 on 2026-04-06 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0015_stationdispatch'),
    ]

    operations = [
        migrations.AddField(
            model_name='stationdispatch',
            name='dispatch_liters2',
            field=models.FloatField(default=0),
        ),
    ]
